server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    resolver ${NGINX_LOCAL_RESOLVERS} valid=5s;
    set $api_backend backend:3000;

    location /api/ {
        proxy_pass http://$api_backend;
        proxy_set_header Host $host;
    }

    location /docs {
        proxy_pass http://$api_backend;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
